// This file is auto-generated by @hey-api/openapi-ts

export const $BranchInfo = {
	type: "object",
	properties: {
		remote: {
			type: "string",
			nullable: true,
			description: "The remote associated with the branch.",
		},
		name: {
			type: "string",
			description: "The name of the branch.",
		},
		kind: {
			type: "string",
			enum: ["Local", "Remote"],
			description: "Indicates whether the branch is local or remote.",
		},
	},
} as const;
