import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import {
	ResizableHandle,
	ResizablePanel,
	ResizablePanelGroup,
} from "@/components/ui/resizable";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="flex min-h-screen">
					<ResizablePanelGroup direction="horizontal" className="min-h-screen">
						<ResizablePanel defaultSize={15} className="min-w-52">
							<NavBar />
						</ResizablePanel>
						<ResizableHandle />
						<ResizablePanel defaultSize={85}>{children}</ResizablePanel>
					</ResizablePanelGroup>
				</main>
			</body>
		</html>
	);
}
