# yaml-language-server: $schema=https://github.com/OAI/OpenAPI-Specification/raw/main/schemas/v3.1/schema.json
openapi: 3.1.0

info:
  title: Server API
  version: 1.0.0
  description: API for commits of a repository.

servers:
  - url: http://127.0.0.1:8823

paths:
  /repo/{repo_path}/commits:
    get:
      summary: Get commits for a repository
      parameters:
        - in: path
          name: repo_path
          schema:
            type: string
          required: true
        - in: query
          name: branch
          schema:
            type: string
          description: The name of the branch
        - in: query
          name: kind
          schema:
            type: string
            enum: [Local, Remote]
          description: Indicates whether the branch or tag is local or remote
      responses:
        "200":
          description: A list of commits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Commit"

components:
  schemas:
    Commit:
      type: object
      properties:
        hash:
          type: string
          description: The commit hash
        author:
          $ref: "#/components/schemas/Person"
        commiter:
          $ref: "#/components/schemas/Person"
        message:
          type: string
          description: The commit message
        summary:
          type: string
          description: The commit summary
        time:
          type: integer
          format: int64
          description: The timestamp of the commit
    Person:
      type: object
      properties:
        name:
          type: string
          description: The name of the person
        email:
          type: string
          description: The email address of the person
      required:
        - name
        - email
